name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version (e.g., 1.0.0)
        required: true
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

env:
  TAG: ${{ github.event.inputs.version }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_TOKEN }}
    
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/avshutov/avs-2048:${TAG}
        docker push --all-tags ghcr.io/avshutov/avs-2048

    - name: Commit new tag
      env:
        valuesFilePath: ./charts/values.yaml
      run: |
        sed -i "s/tag:.*/tag: ${TAG}/g" ${valuesFilePath}
        git config user.name github-actions
        git config --global user.email github-actions@github.com
        git add ${valuesFilePath}
        git commit -m "Automatic tag update"
        git push
